### ISSUE TITLE
Beautify team page

### ISSUE THREAD

**Issue by vsvipul** [vsvipul/Rann-Neeti-2018#3]
Make the team page more good looking ..

**Comment by muskan21jain** [comment]
@vsvipul i am working on this issue.

**Comment by vsvipul** [comment]
@94151 sure.. submit a PR whenever it is ready.. :+1:  also, take care of resposiveness

**Comment by vsvipul** [comment]
@94151  are u still working on this ??

**Comment by muskan21jain** [comment]
@vsvipul I have seen the team page. and it looks me perfect. So i am not working on it.

**Comment by vsvipul** [comment]
anyone else who wants to work on this can work..

**Comment by nimradium** [comment]
> anyone else who wants to work on this can work..

@vsvipul working on it but it may take a while

**Comment by nimradium** [comment]
Satus:

- [x] Transfer to JSON file

- [x] add new team page with home theme

- [x] include JSON file to new team page

- [x] change css

- [ ] make responsive

**Comment by vsvipul** [comment]
transfer to XML may not be needed.. only do that if it makes accessibility better. Only thing needed is the that the team page should not look so dull (white).

**Comment by nimradium** [comment]
> transfer to XML may not be needed.. only do that if it makes accessibility better. Only thing needed is the that the team page should not look so dull (white).

@vsvipul well it is easier to work with XML in this case cause with over 20 team members it is really exhausting to change the html (for example the class) for each one individually

**Comment by vsvipul** [comment]
ok i personally have never done anything in XML.. you can go ahead and do that :+1:  I would also love to see how it is done..

**Comment by nimradium** [comment]
> ok i personally have never done anything in XML.. you can go ahead and do that 👍 I would also love to see that...

@vsvipul well the xml file is very simple I can show it to you when it's finished but implementing it to the page is a bit more difficult

**Comment by vsvipul** [comment]
go ahead and try if u can :+1: ... I'll always be here :)

**Comment by nimradium** [comment]
@vsvipul The XML file will look like [this](https://github.com/nimradium/Rann-Neeti-2018/blob/beautify-teampage/team.xml) (I will make some minor changes to it later)

**Comment by vsvipul** [comment]
looks cool... you can take your time :+1:  meanwhile, i'll assign this issue to you so that no one else works on it..

**Comment by nimradium** [comment]
I have nearly finished building the new team page. I only need to make it responsive but before that I would like you to review my work so I don't have to make some changes twice.

https://nimradium.github.io/Rann-Neeti-2018/team.html

**Comment by vsvipul** [comment]
arranging them according to different categories like design, web development, publicity is very important.. you have not done anything like that on your repo..   make sure u do that, as was the case in the original team page..

**Comment by vsvipul** [comment]
for now, u can just implement json on the previous page and the design part can be taken care of later..

**Comment by nimradium** [comment]
> arranging them according to different categories like design, web development, publicity is very important.. you have not done anything like that on your repo.. make sure u do that, as was the case in the original team page..

working on that just forgot to write that

**Comment by vsvipul** [comment]
then the theme seems fine, i guess, if you are adding responsiveness and categories :+1:

**Comment by nimradium** [comment]
I've now included the category buttons so you can sort them

https://nimradium.github.io/Rann-Neeti-2018/team.html

> then the theme seems fine, i guess, if you are adding responsiveness and categories 👍

- [x] categories
- [ ] responsive

**Comment by vsvipul** [comment]
the animation while switching the categories is gone .. can u do something to restore that as well... everything else seems fine.. :+1: Also, are u working on the responsiveness ?

**Comment by nimradium** [comment]
> the animation while switching the categories is gone .. can u do something to restore that as well... everything else seems fine.. 👍 Also, are u working on the responsiveness ?

Well... the animation is not quite easy cause its hidden somewhere in the 1000 lines of mixitup but I'm trying to find it and implement it in the new page. When I've finished that I'm going to work on the responsiveness

**Comment by vsvipul** [comment]
> > the animation while switching the categories is gone .. can u do something to restore that as well... everything else seems fine.. +1 Also, are u working on the responsiveness ?
> 
> Well... the animation is not quite easy cause its hidden somewhere in the 1000 lines of mixitup but I'm trying to find it and implement it in the new page. When I've finished that I'm going to work on the responsiveness

sure... submit a PR whenever ur ready :+1:

**Comment by nimradium** [comment]
I have tried to find and implement the old animations for some days now but I only found some parts of it and I haven't succeeded in implementing it. I'm going to continue to work on the responsiveness and open a new issue for the animation and gonna document my progress in it, so either someone can continue to work on it or I'm gonna work on it when the page is responsive.
